name: ukk2026_machloanapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: "none"

# App version
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# =========================
# Dependencies
# =========================
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  pdf: ^3.10.8
  printing: ^5.11.1
  go_router: ^14.2.3
  dotted_border: ^2.0.0
  intl: ^0.19.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1

# =========================
# Dev Dependencies
# =========================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# =========================
# Flutter Config
# =========================
flutter:
  uses-material-design: true

  assets:
    - assets/images/mechloan.png
    - assets/images/mesinkiri.png
    - assets/images/mesinkanan.png
